<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>BenchBarTray.WinUI</AssemblyName>
    <RootNamespace>BenchBar.Tray.WinUI</RootNamespace>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained Condition="'$(WindowsAppSDKSelfContained)' == ''">true</WindowsAppSDKSelfContained>
    <EnableMsixTooling>true</EnableMsixTooling>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="H.NotifyIcon.WinUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tray.Core\Tray.Core.csproj" />
  </ItemGroup>

</Project>
