<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>BenchBar.Tray.Core</AssemblyName>
    <RootNamespace>BenchBar.Tray.Core</RootNamespace>
    <OutputType>Library</OutputType>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Tray.Core.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
</Project>
